import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle,AiFillLinkedin,AiFillYoutube} from 'react-icons/ai';
import Image from 'next/image';
import profile from "../../public/profile_image.png";
import product1 from "../../public/product1.png";
import product2 from "../../public/product2.png";
import product3 from "../../public/product3.png";
import product4 from "../../public/product4.png";
import project1 from "../../public/projects1.jpg";
import { useState } from 'react';

export default function Home() {

  const [darkMode,setDarkMode]=useState(false);
  return (
    <>
    <div className={darkMode?'dark':''}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl dark:text-white'>Ayush</h1>
          <ul className='flex items-center'>
            <li><BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white'/></li>
        <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-2 py-2 rounded-md ml-8' href="#">Resume</a></li>
        </ul>        
        </nav>
        <div className='text-center p-10'>
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl '>AYUSH PATHAK</h2>
          <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Software Developer</h3>
          <p className='text-md py-5 leading-8 text-gray-800 md:text-xl mx-w-lg mx-auto dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam, praesentium!</p>
        </div>
        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white'>
          <AiFillTwitterCircle/>
          <AiFillLinkedin/>
          <AiFillYoutube/>
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
          <Image src={profile}/>
        </div>
        </section>
        <section>
          <div className='dark:text-white'>
            <h3 className='text-3xl py-1 mt-8 dark:text-white'>Service I Offer :-</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit.
            <span className='text-teal-500 '>Ducimus aperiam</span>  eligendi temporibus at tempore, odit quia consequatur nemo. Sit, possimus <span className='text-teal-500'>Ducimus aperiam</span> voluptatibus.</p>
          <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit.
           eligendi temporibus at tempore, odit quia consequatur nemo. Sit, possimus</p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-2xl p-10 rounded-xl my-10 dark:bg-orange-400'>
              <Image src={product1} width={185} height={185} className='mx-auto'/>
              <h3 className='text-lg font-bold pt-8 pb-2'>Lorem ipsum dolor sit.</h3>
              <p className='py-2'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, optio culpa. Quibusdam at voluptatem accusantium ex molestiae hic?</p>
              <h4 className='py-4 text-teal-600'>Lorem ipsum dolor sit amet.</h4>
              <p className='text-gray-800 py-1'>Lorem, ipsum.</p>
              <p className='text-gray-800 py-1'>Lorem, ipsum.</p>
              <p className='text-gray-800 py-1'>Lorem, ipsum.</p>
              <p className='text-gray-800 py-1'>Lorem, ipsum.</p>
            </div>          
            <div className='text-center shadow-2xl p-10 rounded-xl my-10 dark:bg-orange-400'>
              <Image src={product2} width={185} height={185} className='mx-auto'/>
              <h3 className='text-lg font-bold pt-8 pb-2'>Lorem ipsum dolor sit.</h3>
              <p className='py-2'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, optio culpa. Quibusdam at voluptatem accusantium ex molestiae hic?</p>
              <h4 className='py-4 text-teal-600'>Lorem ipsum dolor sit amet.</h4>
              <p className='text-gray-800 py-1'>Lorem, ipsum.</p>
              <p className='text-gray-800 py-1'>Lorem, ipsum.</p>
              <p className='text-gray-800 py-1'>Lorem, ipsum.</p>
              <p className='text-gray-800 py-1'>Lorem, ipsum.</p>
            </div>                   
            <div className='text-center shadow-2xl p-10 rounded-xl my-10 dark:bg-orange-400'>
              <Image src={product3} width={230} height={230} className='mx-auto'/>
              <h3 className='text-lg font-bold pt-8 pb-2'>Lorem ipsum dolor sit.</h3>
              <p className='py-2'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, optio culpa. Quibusdam at voluptatem accusantium ex molestiae hic?</p>
              <h4 className='py-4 text-teal-600'>Lorem ipsum dolor sit amet.</h4>
              <p className='text-gray-800 py-1'>Lorem, ipsum.</p>
              <p className='text-gray-800 py-1'>Lorem, ipsum.</p>
              <p className='text-gray-800 py-1'>Lorem, ipsum.</p>
              <p className='text-gray-800 py-1'>Lorem, ipsum.</p>
            </div>     
            </div>    
            <div className='dark:text-white'>
          <h3 className='text-3xl py-1 '>Portfolio</h3>
          <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit.
            <span className='text-teal-500'>Ducimus aperiam</span>  eligendi temporibus at tempore, odit quia consequatur nemo. Sit, possimus <span className='text-teal-500'>Ducimus aperiam</span> voluptatibus.</p>
          <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit.
           eligendi temporibus at tempore, odit quia consequatur nemo. Sit, possimus</p>
    </div>
        <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
          <div className=' basis-1/3 flex-1'>
            <Image src={project1} className='rounded-lg object-cover'/>
            </div>        
        <div className=' basis-1/3 flex-1'>          
            <Image src={project1}  className='rounded-lg object-cover'/>            
        </div>
        </div>
        </section>        
      </main>
      </div>
    </>
  )
}
